### ISSUE TITLE
DA events

### ISSUE THREAD

**Issue by waynelen6** [Dani3lSun/apex-plugin-apexsignature#4]
Hai,

Possible to guide me how to create component dynamic action like clear/save?
https://www.dropbox.com/s/civ1fwvu2vqa7bi/Untitled.png?dl=0
I was try to create DA like this, but its not working. And what should I put in True Action?

Thanks you

**Comment by Dani3lSun** [comment]
Hi @waynelen6 ,
just have a look at the demo app, in there is a working example:
https://github.com/Dani3lSun/apex-plugin-apexsignature/releases/tag/v1.1
But the static ID of the buttons are used inside the region settings not in a DA... the DA events fire when an event already happened, so basically after save or clear...These events can be used to execute additional things, e.g refresh a region. But selction type in the "when" section of an DA is always the region it self, because the region is triggering the DA event...

**Comment by waynelen6** [comment]
Thank you so much @Dani3lSun, I understand and got it now.
